language: bash
sudo: required
dist: trusty
services:
- docker
git:
  depth: 1
  submodules: false
branches:
  only:
  - main
cache:
  directories:
  - node_modules
env:
  global:
  - PATH=$HOME/.local/bin:$PATH
  - CI=true
before_install:
- echo "Before Install..."
install:
- docker run -e CI=true -i -t -v ${PWD}/:/app/ --workdir /app/ node:14-stretch npm install
before_script:
- docker run -e CI=true -i -t -v ${PWD}/:/app/ --workdir /app/ node:14-stretch npm test -- --coverage
script:
- docker run -e CI=true -i -t -v ${PWD}/:/app/ --workdir /app/ node:14-stretch npm run-script build
after_script:
- echo "After Script..."
before_cache:
- echo "Before Cache..."
after_success:
- echo "After Success..."
after_failure:
- echo "After Failure..."
before_deploy:
- echo "Before Deploy..."
deploy:
  - provider: script
    script: docker run -e CI=true -e NPM_TOKEN="${NPM_TOKEN}" -i -t -v ${PWD}/:/app/ --workdir /app/ node:14-stretch bash -c 'npm config set "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" && npm publish'
    on:
      branch: main
    skip_cleanup: true
  - provider: pages
    local_dir: ${PWD}/build/
    skip_cleanup: true
    github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
    keep_history: true
    on:
      branch: main
after_deploy:
  - echo "After Deploy..."
